### ISSUE TITLE
is there a api to change the user password?

### ISSUE THREAD

**Issue by bpceee** [NodeBB/nodebb-plugin-write-api#20]
or is there gonna be one?

**Comment by bpceee** [comment]
anyway, I implemented it. 
please check the pull-request.
thanks~

**Comment by julianlam** [comment]
Seems you've implemented it on your own, so let me know if you still need this :smile:

**Comment by Fidelix** [comment]
This would be beneficial to my project, but I still don't know how to do it....

**Comment by julianlam** [comment]
Okay, will keep this open
